
name: Pull Request

on:
  #By default, a workflow only runs when a pull_request event's activity type is opened, synchronize, or reopened.
  pull_request:
  push:
    branches:
      - main

jobs:
  frontend-tests:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        name: Setup Node version 16q
        with:
          node-version-file: frontend/.nvmrc
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci # https://docs.npmjs.com/cli/v8/commands/npm-ci
        working-directory: ./frontend

      - name: Run frontend tests
        run: npm test
        working-directory: ./frontend

  backend-tests:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python version 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'

      - name: Install python dependencies
        run: if [ -f requirements.txt ]; then pip3 install -r requirements.txt ; fi

      - name: Run backend tests
        run: pytest